#!/bin/bash -u

enable="${enable:-n}"
autostart="${autostart:-n}"

# CentOS v7
[[ -r /etc/centos-release ]] && grep -sq 'CentOS Linux release 7' /etc/centos-release && yum -y install epel-release && yum -y install salt-minion && echo 'OK: minion init as cent7' && [[ "${enable}" =~ ^[yY] ]] && systemctl start salt-minion && [[ "${autostart}" =~ ^[yY] ]] && systemctl enable salt-minion 

# CentOS v6
[[ -r /etc/centos-release ]] && grep -sq 'CentOS release 6' /etc/centos-release && yum -y install epel-release && sed -i 's/https/http/' /etc/yum.repos.d/epel.repo && yum -y install salt-minion && [[ "${enable}" =~ ^[yY] ]] && service salt-minion start && [[ "${autostart}" =~ ^[yY] ]] && chkconfig salt-minion on && echo 'OK: minion init as cent6'

# CentOS v5
[[ -r /etc/redhat-release ]] && grep -sq 'CentOS release 5' /etc/redhat-release && echo epel-release python-hashlib |xargs -n1 yum -y install && curl -Lk https://copr.fedorainfracloud.org/coprs/saltstack/salt-el5/repo/epel-5/saltstack-salt-el5-epel-5.repo -o /etc/yum.repos.d/saltstack-copr.repo && cd $(mktemp -d) && curl -Lk https://copr-be.cloud.fedoraproject.org/results/saltstack/salt-el5/pubkey.gpg -o pubkey.gpg && rpm --import pubkey.gpg && yum -y install salt-minion && echo 'OK: minion init as cent5' && [[ "${enable}" =~ ^[yY] ]] && /sbin/service salt-minion start && [[ "${autostart}" =~ ^[yY] ]] && /sbin/chkconfig salt-minion on 

# end on a high note
exit 0
